name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: node -v && npm -v && npm ci
      - name: Build
        run: npm run build && ls -la dist
      - name: Upload artifact (dist folder)
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dist
          path: ./dist
      - name: Test
        run: npm run test
